### ISSUE TITLE
[Bug] Cannot find module '@storybook/addon-svelte-csf' after update.

### ISSUE THREAD

**Issue by olafurw** [storybookjs/addon-svelte-csf#117]
### Describe the bug

After I update to the new 3.0.5 from the 3.0.3 version of `@storybook/addon-svelte-csf` I get this error from `svelte-check`

```
Error: Cannot find module '@storybook/addon-svelte-csf' or its corresponding type declarations. (ts)
<script lang="ts">
    import { Meta, Story } from '@storybook/addon-svelte-csf';
```

The package is there, it's installed. I tried reinstalling all of the packages but the error is still there. I'm not sure if this is a `svelte-check` error or something that's missing from the `@storybook/addon-svelte-csf` package.

### Steps to reproduce the behavior

Repo: https://github.com/olafurw/addon-svelte-csf-import-bug

### Environment

Node version: v18.16.0
npm version: v9.7.2
Operating System: linux 6.4.6-200.fc38.x86_64

**Comment by hobbes7878** [comment]
Should be fixed in https://github.com/storybookjs/addon-svelte-csf/pull/115

**Comment by olafurw** [comment]
I updated the repo branch to use the 3.0.6 and it's still failing. Also checked on my main project's branch, same.

Here's the runner with the error. https://github.com/olafurw/addon-svelte-csf-import-bug/actions/runs/5725774944/job/15514917402

**Comment by hobbes7878** [comment]
OK, gonna look more closely at what's going on, but closing this issue in favour of one nipped in before you: https://github.com/storybookjs/addon-svelte-csf/issues/116

**Comment by olafurw** [comment]
Closing the one that has a github repo that reproduces the bug in favor one that just says there's a bug? Odd. Hope you fix it soon.

**Comment by hobbes7878** [comment]
Sorry, mate. First come/first served world... Check the proposed update to your tsconfig in that linked issue to see if that fixes it for ya.

**Comment by olafurw** [comment]
> First come/first served world

By definition then people that spend time to create a reproduction will be closed, so why would someone spend time to help you narrow down why a bug is occurring when it's just going to be closed in favor of someone that posted the error message?

I know I'm not going to in the future, sorry.

**Comment by JReinhold** [comment]
Thanks for your reproduction and bug report @olafurw . I think what @hobbes7878 was referring to, was that the conversation at #116 has more details that are valuable to fixing the issue.

I'll merge over your report to that issue, so we also have a reproduction.
