### ISSUE TITLE
[Bug] Could not resolve dependency @storybook/svelte@"^6.2.9" from @storybook/addon-svelte-csf@1.1.0

### ISSUE THREAD

**Issue by francoisromain** [storybookjs/addon-svelte-csf#44]
### Describe the bug

It makes an dependency error, when I try to install `addon-svelte-csf` with the the following config : 

```
    "@storybook/addon-docs": "6.5.0-alpha.55",
    "@storybook/addon-essentials": "^6.5.0-alpha.55",
    "@storybook/addon-links": "^6.5.0-alpha.55",
    "@storybook/builder-vite": "^0.1.24",
    "@storybook/svelte": "6.5.0-alpha.55",
```

### Steps to reproduce the behavior

1. `npm i -D @storybook/addon-svelte-csf` 
2. See error

```
Could not resolve dependency:
npm ERR! peer @storybook/svelte@"^6.2.9" from @storybook/addon-svelte-csf@1.1.0
```

### Expected behavior

No error. 

### Additional context
I can force the install with `npm i -f`. 
It works, but it is not doable in every environments (ie: CI). 

What can I do to fix this? 
Thank you

**Comment by j3rem1e** [comment]
https://github.com/storybookjs/addon-svelte-csf/pull/42

**Comment by j3rem1e** [comment]
Fixed in 2.0.1

**Comment by francoisromain** [comment]
Sorry, my PR still didn't fix the issue. 
I still have the same error: 

```
❯ npm i -D @storybook/addon-svelte-csf
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! Found: @storybook/svelte@6.5.0-alpha.64
npm ERR! node_modules/@storybook/svelte
npm ERR!   dev @storybook/svelte@"^6.5.0-alpha.64" from the root project
npm ERR! Could not resolve dependency:
npm ERR! peer @storybook/svelte@">=6.4.20" from @storybook/addon-svelte-csf@2.0.3
```
@j3rem1e any idea on how to fix that please?

thank you

**Comment by j3rem1e** [comment]
It's expected, the matcher ">=6.4.20" doesn't select prerelease version.

You can use `--force` to use a prerelease version.

**Comment by francoisromain** [comment]
ok. 
The problem is I can not use `--force` in the CI.
